version: "3"
services:
  reverseproxy:
      image: gmpatil/udgm-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: gmpatil/udgm-api-user
    environment:
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_DIALECT: $DB_DIALECT
      JWT_SECRET: $JWT_SECRET
      FE_URL: "http://localhost:8100"
  backend-feed:
    image: gmpatil/udgm-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_DIALECT: $DB_DIALECT
      aws_region: $aws_region
      aws_profile: $aws_profile
      aws_s3_bucket: $aws_s3_bucket
      JWT_SECRET: $JWT_SECRET
      FE_URL: "http://localhost:8100"
  frontend:
    image: gmpatil/udgm-frontend:local
    ports:
      - "8100:80"
