version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: gmpatil/udgm-reverseproxy 
  backend_user:
    build:
      context: ../../user
    image: gmpatil/udgm-api-user
  backend_feed:
    build:
      context: ../../feed  
    image: gmpatil/udgm-api-feed
  frontend:
    build:
      context: ../../frontend  
    image: gmpatil/udgm-frontend:local
