apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user  
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: gmpatil/udgm-api-user
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        ports:
          - containerPort: 8080                 
        env:
        - name: FE_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: FE_URL 
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: DB_DIALECT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_DIALECT               
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_USERNAME
      restartPolicy: Always


