apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed  
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: gmpatil/udgm-api-feed
        name: backend-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: FE_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: FE_URL
        - name: aws_s3_bucket
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: aws_s3_bucket
        - name: aws_profile
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: aws_profile
        - name: aws_region
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: aws_region
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: DB_DIALECT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_DIALECT                
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_USERNAME      
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret       